sonar.projectKey=mediqux-mobile
sonar.projectName=Mediqux Mobile
sonar.projectVersion=1.0.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.flutter.coverage.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gen.dart
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/main.dart
